apiVersion: apps/v1
kind: Deployment
metadata:
  name: versioned-echo-v2
  labels: { app: versioned-echo, version: v2 }
spec:
  replicas: 2
  selector:
    matchLabels: { app: versioned-echo, version: v2 }
  template:
    metadata:
      labels: { app: versioned-echo, version: v2 }
    spec:
      containers:
        - name: versioned-echo
          image: versioned-echo:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_VERSION
              value: "v2"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 2
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 2
