services:
  analytics-service:
    container_name: analytics-service
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DYNAMODB_TABLE=analytics_events
      - AWS_SQS_URL=http://localstack:4566/000000000000/toggle-analytics-queue
      - PORT=8005
      - ENVIRONMENT=local
    restart: unless-stopped
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - toggle-net

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://toggleuser:password@db-auth:5432/togglemasterauth
      - MASTER_KEY=01cf4be5-5270-41ff-86fe-0ce789440f04
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      db-auth:
        condition: service_healthy
    networks:
      - toggle-net

  flag-service:
    container_name: flag-service
    build:
      context: ./flag-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=postgresql://toggleuser:password@db-flag:5432/togglemasterflag
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      db-flag:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - toggle-net

  targeting-service:
    container_name: targeting-service
    build:
      context: ./targeting-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - DATABASE_URL=postgresql://toggleuser:password@db-targeting:5432/togglemastertarget
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      db-targeting:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - toggle-net

  evaluation-service:
    container_name: evaluation-service
    build:
      context: ./evaluation-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - REDIS_URL=redis://redis-evaluation:6379
      - FLAG_SERVICE_URL=http://flag-service:8002
      - TARGETING_SERVICE_URL=http://targeting-service:8003
      - AWS_REGION=us-east-1
      - AWS_SQS_URL=http://localstack:4566/000000000000/toggle-analytics-queue
      - SERVICE_API_KEY=tm_key_964a7e906ebb793276abfa60bed76de70e27314359a52184d620d4396873358c 
      # Essa SERVICE_API_KEY foi criada manualmente no auth-service usando a MASTER_KEY. 
      # Para funcionar dinâmicamente, após criada no auth-service, deve-se injetar essa chave (via `Secret`) aqui no `evaluation-service` 
      # ** Considerando o próximo step da evolução para K8s
    depends_on:
      redis-evaluation:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - toggle-net

  db-auth:
    image: postgres:13
    container_name: db-auth
    environment:
      - POSTGRES_USER=toggleuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=togglemasterauth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data/
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toggleuser -d togglemasterauth"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - toggle-net

  db-flag:
    image: postgres:13
    container_name: db-flag
    environment:
      - POSTGRES_USER=toggleuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=togglemasterflag
    ports:
      - "5434:5432"
    volumes:
      - postgres_flag_data:/var/lib/postgresql/data/
      - ./flag-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toggleuser -d togglemasterflag"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - toggle-net

  db-targeting:
    image: postgres:13
    container_name: db-targeting
    environment:
      - POSTGRES_USER=toggleuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=togglemastertarget
    ports:
      - "5435:5432"
    volumes:
      - postgres_target_data:/var/lib/postgresql/data/
      - ./targeting-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toggleuser -d togglemastertarget"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - toggle-net

  redis-evaluation:
    image: redis:latest
    container_name: redis-evaluation
    ports:
      - "6379:6379"
    volumes:
      - redis_evaluation_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - toggle-net

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,dynamodb,ssm,secretsmanager
      - DEBUG=0
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DISABLE_CORS_HEADERS=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack-data:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - toggle-net

volumes:
  postgres_auth_data:
  postgres_flag_data:
  postgres_target_data:
  redis_evaluation_data:

networks:
  toggle-net:
    driver: bridge
