services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-terraform
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,ec2,dynamodb,ssm,secretsmanager
      - DEBUG=0
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DISABLE_CORS_HEADERS=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack-data:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - toggle-net

networks:
  toggle-net:
    driver: bridge
