apiVersion: v1
kind: Service
metadata:
  name: app-health-demo
  namespace: app-health-demo
spec:
  selector:
    app: app-health-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
