apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: keda-demo
type: Opaque
data:
  # amqp://user:pass@rabbitmq.keda-demo.svc.cluster.local:5672/%2f
  connection: YW1xcDovL3VzZXI6cGFzc0ByYWJiaXRtcS5rZWRhLWRlbW8uc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi8lMmY=
  user: dXNlcg==
  password: cGFzcw==
