[package]
name = "service-a"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rustls = "0.21"
rustls-pemfile = "1.0"
anyhow = "1"
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
