apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: versioned-echo
spec:
  replicas: 4
  strategy:
    canary:
      canaryService: versioned-echo-canary
      stableService: versioned-echo
      steps:
      - setWeight: 10
      - pause: { duration: 60 }
      - setWeight: 30
      - pause: { duration: 120 }
      - setWeight: 60
      - pause: { duration: 180 }
  selector:
    matchLabels:
      app: versioned-echo
  template:
    metadata:
      labels:
        app: versioned-echo
    spec:
      containers:
      - name: versioned-echo
        image: versioned-echo:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: versioned-echo
spec:
  selector:
    app: versioned-echo
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: versioned-echo-canary
spec:
  selector:
    app: versioned-echo
  ports:
  - port: 80
    targetPort: 8080
