apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myrustapp.fullname" . }}-config
  labels:
    {{- include "myrustapp.labels" . | nindent 4 }}
data:
  greeting: {{ .Values.config.greeting | quote }}
