apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mini-karpenter-rs
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "configmaps", "namespaces"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
