apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mini-karpenter-rs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mini-karpenter-rs
subjects:
- kind: ServiceAccount
  name: mini-karpenter-rs
  namespace: aula07
