apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: toggle-master
data:
  PORT: "8004"
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://172.18.0.1:4566
  AWS_SQS_URL: http://172.18.0.1:4566/000000000000/toggle-analytics-queue
  AUTH_SERVICE_URL: http://auth-service:8001
  FLAG_SERVICE_URL: http://flag-service:8002
  TARGETING_SERVICE_URL: http://targeting-service:8003
  REDIS_URL: redis://172.18.0.1:6379
  LOG_LEVEL: "DEBUG"
