apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: toggle-master
data:
  PORT: "8004"
  AWS_REGION: us-east-1
  AWS_SQS_URL: https://sqs.us-east-1.amazonaws.com/730335657012/toggle-analytics-queue
  AUTH_SERVICE_URL: http://auth-service:8001
  FLAG_SERVICE_URL: http://flag-service:8002
  TARGETING_SERVICE_URL: http://targeting-service:8003
  REDIS_URL: rediss://redis-evaluation-oyqbvo.serverless.use1.cache.amazonaws.com:6379
  LOG_LEVEL: "DEBUG"
