apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-app
  namespace: aula02
  labels: { app: stable }
spec:
  replicas: 6
  selector:
    matchLabels: { app: stable }
  template:
    metadata:
      labels: { app: stable }
    spec:
      containers:
        - name: app
          image: aula02-scheduler-demo:demo
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 5
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: stable
