apiVersion: apps/v1
kind: Deployment
metadata:
  name: noisy-canary
  namespace: aula02
  labels: { app: noisy }
spec:
  replicas: 2
  selector:
    matchLabels: { app: noisy }
  template:
    metadata:
      labels: { app: noisy }
    spec:
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "noisy"
          effect: "NoSchedule"
      nodeSelector:
        workload: "noisy"
      containers:
        - name: app
          image: aula02-scheduler-demo:demo
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"
          lifecycle:
            postStart:
              exec:
                command: ["sh","-lc","curl -s -X POST 'http://127.0.0.1:8080/busy?ms=120000&threads=2' >/dev/null 2>&1 &"]
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 5
