apiVersion: apps/v1
kind: Deployment
metadata:
  name: besteffort-worker
  namespace: aula02
  labels: { app: besteffort }
spec:
  replicas: 3
  selector:
    matchLabels: { app: besteffort }
  template:
    metadata:
      labels: { app: besteffort }
    spec:
      containers:
        - name: app
          image: aula02-scheduler-demo:demo
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 5
