apiVersion: apps/v1
kind: Deployment
metadata:
  name: burstable-worker
  namespace: aula02
  labels: { app: burstable }
spec:
  replicas: 3
  selector:
    matchLabels: { app: burstable }
  template:
    metadata:
      labels: { app: burstable }
    spec:
      containers:
        - name: app
          image: aula02-scheduler-demo:demo
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 5
