name: üöÄ SAM Multi-Environment Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # ========================================
  # JOB 1: Deploy homolog
  # ========================================
  deploy-homolog:
    name: üß™ Deploy homolog
    runs-on: ubuntu-latest
    environment: homolog
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - uses: aws-actions/setup-sam@v2
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: üî® SAM Build
        run: sam build --template-file fase_3/aulas/1_ci_cd/hands_on/6_aula/template.yml
      
      - name: üß™ Deploy homolog
        run: |
          sam deploy --config-env homolog \
            --template-file fase_3/aulas/1_ci_cd/hands_on/6_aula/template.yml \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
      
      - name: üìã URL homolog
        run: |
          aws cloudformation describe-stacks \
            --stack-name fiap-serverless-homolog \
            --query 'Stacks[0].Outputs' --output table

  # ========================================
  # JOB 2: Deploy Production
  # ========================================
  deploy-production:
    name: üè≠ Deploy Production
    runs-on: ubuntu-latest
    needs: deploy-homolog
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - uses: aws-actions/setup-sam@v2
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: üî® SAM Build
        run: sam build --template-file fase_3/aulas/1_ci_cd/hands_on/6_aula/template.yml \
      
      - name: üè≠ Deploy Production
        run: |
          sam deploy --config-env production \
            --template-file fase_3/aulas/1_ci_cd/hands_on/6_aula/template.yml \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
      
      - name: üìã URL Production
        run: |
          aws cloudformation describe-stacks \
            --stack-name fiap-serverless-prod \
            --query 'Stacks[0].Outputs' --output table
