name: ğŸ—ï¸ Multi-Environment

on:
  push:
    branches: [ develop, homolog ]

jobs:
  deploy-dev:
    name: ğŸ”§ Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
      
      - name: ğŸ”§ Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: ğŸ”‘ Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: âš™ï¸ Init & Deploy Dev
        working-directory: fase_3/aulas/1_ci_cd/hands_on/5_aula/terraform/environments/development
        run: |
          terraform init
          terraform apply -auto-approve

  deploy-homolog:
    name: ğŸ§ª homolog  
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homolog'
    
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
      
      - name: ğŸ”§ Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: ğŸ”‘ Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: âš™ï¸ Init & Deploy homolog
        working-directory: fase_3/aulas/1_ci_cd/hands_on/5_aula/terraform/environments/homolog
        run: |
          terraform init
          terraform apply -auto-approve
