name: ğŸš€ SAM Pipeline CI/CD

on:
  push:
    branches: [ 'homolog' ]
  workflow_dispatch:

jobs:
  # ========================================
  # JOB 1: Build e Deploy
  # ========================================
  deploy:
    name: ğŸš€ Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
      
      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: ğŸ”§ Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      
      - name: ğŸ”‘ Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: ğŸ”¨ SAM Build
        run: sam build --template-file fase_3/aulas/1_ci_cd/hands_on/6_aula/template.yml
      
      - name: ğŸš€ SAM Deploy
        run: |
          sam deploy \
            --template-file fase_3/aulas/1_ci_cd/hands_on/6_aula/template.yml \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
      
      - name: ğŸ“‹ Mostrar URL da API
        run: |
          aws cloudformation describe-stacks \
            --stack-name fiap-serverless-dev \
            --query 'Stacks[0].Outputs' \
            --output table
