apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-pending
  namespace: aula07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-pending
  template:
    metadata:
      labels:
        app: demo-pending
      annotations:
        prefer-spot: "true"
    spec:
      nodeSelector:
        demo/require-gpu: "true"
        topology.kubernetes.io/zone: "us-east-1a"
      containers:
      - name: sleeper
        image: busybox:1.36
        command: ["sh","-c","sleep 36000"]
        resources:
          requests:
            cpu: "1500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1Gi"
